### ISSUE TITLE
Strip byte order mark

### ISSUE THREAD

**Issue by agitter** [manubot/manubot#125]
In https://github.com/manubot/rootstock/issues/247 a leading byte order mark prevented a section header from rendering correctly.  Should Manubot strip this from the source markdown in
https://github.com/manubot/manubot/blob/025b7c78e96d37cb81388bf739411dfe82969780/manubot/process/manuscript.py#L37

**Comment by agitter** [comment]
This Stack Overview [answer](https://stackoverflow.com/a/45099125) gives two options:
- `lstrip` the '\ufeff' if present
- open with the `utf-8-sig` encoding

We can specifying an encoding here
https://github.com/manubot/manubot/blob/025b7c78e96d37cb81388bf739411dfe82969780/manubot/process/manuscript.py#L35

Per the [`open` docs](https://docs.python.org/3/library/functions.html#open)
> The default encoding is platform dependent (whatever `locale.getpreferredencoding()` returns), but any text encoding supported by Python can be used.

The [`utf_8_sig` encoding](https://docs.python.org/3/library/codecs.html#module-encodings.utf_8_sig) allows an optional byte order mark.  Could we ever read Markdown files that are not UTF-8 encoded?

**Comment by dhimmel** [comment]
From [pandoc's manual](https://pandoc.org/MANUAL.html#character-encoding):

> Pandoc uses the UTF-8 character encoding for both input and output. If your local character encoding is not UTF-8, you should pipe input and output through [`iconv`](http://www.gnu.org/software/libiconv/)

I believe Pandoc removes the BOM at the start of a file ([haskell](https://github.com/jgm/pandoc/blob/f3080c0c22470e7ecccbef86c1cd0b1339a6de9b/src/Text/Pandoc/UTF8.hs#L101-L109), https://github.com/jgm/pandoc/issues/743). However, Pandoc does not output BOMs as per https://github.com/jgm/pandoc/issues/3312.

Here is a script to check whether pandoc removes a BOM:

```bash
printf '\xEF\xBB\xBFtext\n' > pandoc-input.md
pandoc --output=pandoc-output.md pandoc-input.md
file pandoc-input.md pandoc-output.md
```

With pandoc 2.7.2, I got the following output:

```
pandoc-input.md:  UTF-8 Unicode (with BOM) text
pandoc-output.md: ASCII text
```

Therefore, it does look like the Pandoc removed the BOM rather than passing it through. I think this behavior of removing BOM from input (and outputting without BOM) makes sense for us. Seems like we could achieve this by reading content files using `utf_8_sig`. The current behavior of not removing BOMs, causing them to end up in the middle of a document, doesn't make sense and causes issues like https://github.com/manubot/rootstock/issues/247.

> Could we ever read Markdown files that are not UTF-8 encoded?

I think we should stick with the Pandoc behavior of requiring UTF-8. My understanding is that the inclusion of a BOM is valid UTF-8, therefore we should be able to read it.
