### ISSUE TITLE
Apply a consistent & standard style for Python formatting

### ISSUE THREAD

**Issue by epogrebnyak** [manubot/manubot#152]
When submitting/reviewing PR's we spend a bit of time doing trivial changes of code formatting, which can be automated, eg with `autopep8` or `black`.

`autopep8` has an aggressive more which moves a lot of formatting: 

```
autopep8 -iaa filename
```

There is a softer version (just deals with trailing whitespace):

```
autopep8 -i filename --select W29
```

We need something in between to be able to apply regularly either just to new code or to all of codebase.

**Comment by dhimmel** [comment]
I'm in favor of switching to black because it's the only one that makes almost all formatting decisions. From what I've seen, sometimes black will make bad decisions. In these cases, we can disable it with the `# fmt: on/off` comments.

We can blacken the codebase and enforce it via CI.

But let's try to merge all open PRs first that are not on hold.

**Comment by epogrebnyak** [comment]
Answered as a question, can reopen later.

**Comment by dhimmel** [comment]
Actually let's keep open until we implement a consistent code style to the repo. I think it's a good idea and perhaps we can do it after the current round of PRs (but perhaps before citekey classes)?
