### ISSUE TITLE
Citations for Clinical Trials

### ISSUE THREAD

**Issue by rando2** [manubot/manubot#216]
Hello from the use case over at [COVID-19 Review](https://github.com/greenelab/covid19-review)!

We're running into an issue where we need to cite [clinical trial identifiers](https://blogs.uoregon.edu/annie/2017/10/25/clinical-trial-apa-format/). These are alphanumeric strings that refer to records at https://clinicaltrials.gov/ . 

Typically, a user will search for the string, though it does also seem like there is a fairly clean URL associated with each record (e.g., `https://clinicaltrials.gov/ct2/show/NCT00532493` is mentioned in the University of Oregon site linked above).

The problem is it's not totally evident when you visit a clinical trial record what the static URL would be. For example, if I use the clinicaltrials.gov site to search for one of the clinical trials referred to in [this pull request](https://github.com/greenelab/covid19-review/pull/111), I see:
`https://clinicaltrials.gov/ct2/show/NCT04292899?cond=NCT04292899&draw=2&rank=1` 
Our contributors (for the most part) aren't likely to know how to clean up a URL like this.

I wanted to touch base and see whether clinical trials are a type of citation manubot would be able to support (or that you'd be interested to add). Otherwise, do you have any advice about how to best approach citing this type of resource?  In case it helps, they are somewhat [supported by PubMed](https://www.nlm.nih.gov/pubs/techbull/mj05/mj05_ct.html), but as a secondary source identifier.

Tagging @cgreene in case he has anything else to add.

Thank you very much!

**Comment by cgreene** [comment]
I'm imagining the citation would go something like:
Study Director. Full Title. Accession.

Here's an example link: https://clinicaltrials.gov/ct2/show/NCT04292899

There is an API here: https://clinicaltrials.gov/api/query/full_studies?expr=NCT04292899&fmt=JSON

**Comment by dhimmel** [comment]
One option is to use hyperlinks instead of citations, like I did for this clinical trial mention in the [Project Rephetio manuscript](https://git.dhimmel.com/rephetio-manuscript/#nicotine-dependence-case-study):

```markdown
Galantamine, an approved Alzheimer's treatment, is currently in [Phase 2 trial](https://clinicaltrials.gov/ct2/show/NCT01669538 "Effect of Galantamine on Short-term Abstinence (GAL-K)") for smoking cessation and is showing promising results [@doi:10.1038/tp.2015.209].
```

But if you'd like to have reference items for clinical trials, I think the best way currently would be to do `@url:https://clinicaltrials.gov/ct2/show/NCT04292899`.

Let's see how Manubot will render the metadata generated for both URLs (the second URL having search related parameters set in a query string):

```shell
manubot cite --render --format=markdown \
  'url:https://clinicaltrials.gov/ct2/show/NCT04292899' \
  'url:https://clinicaltrials.gov/ct2/show/NCT04292899?cond=NCT04292899&draw=2&rank=1'
```

Both citations come out the same:

1. **Study to Evaluate the Safety and Antiviral Activity of Remdesivir (GS-5734™) in Participants With Severe Coronavirus Disease (COVID-19) - Full Text View - ClinicalTrials.gov**<https://clinicaltrials.gov/ct2/show/NCT04292899>

2. **Study to Evaluate the Safety and Antiviral Activity of Remdesivir (GS-5734™) in Participants With Severe Coronavirus Disease (COVID-19) - Full Text View - ClinicalTrials.gov**<https://clinicaltrials.gov/ct2/show/NCT04292899>

The query string is not part of the citation URL probably because the webpage contains:

```html
<meta property="og:url" content="https://clinicaltrials.gov/ct2/show/NCT04291053">
```

The title is correct expect for including " - Full Text View - ClinicalTrials.gov". There is no author, publisher, or date. But the URL is correct. I'd go ahead and start citing clinical trials like this. You can always fix the metadata manually in `manual-references.json`. Sometimes it's easiest to merge PRs without perfect references and fix the reference in bulk manually at a later stage.

The best long term solution would be for zotero/translation-server to add a transator for clinicaltrials.gov URLs as has been suggested in https://github.com/zotero/translators/issues/1952. If you have any javascript developers interested in your project, perhaps this is one way they could help.

**Comment by rando2** [comment]
Thanks @dhimmel . I've asked if anyone knows JavaScript -- no one has mentioned it in their bio, so we'll see!

**Comment by rdvelazquez** [comment]
@ressy and I are looking into this now. Looks doable🤞

**Comment by dhimmel** [comment]
Cool! I haven't explored how hard it is to create a new translator, but if you decide to try to tackle this task, perhaps comment on https://github.com/zotero/translators/issues/1952 so others zotero folks can give you guidance.

**Comment by agitter** [comment]
@dhimmel what do you think about adding a new type of identifier in Manubot as a wrapper around the URL?  I'm imagining a shorthand sytax like `trial:NCT04292899` instead of `url:https://clinicaltrials.gov/ct2/show/NCT04292899`.

One concern is that `trial` is too ambiguous.  There are other clinical trials databases like https://www.clinicaltrialsregister.eu/ctr-search/search and http://www.who.int/ictrp/en/.  "Trial" could also refer to a legal trial (e.g. https://github.com/manubot/manubot/issues/1).

**Comment by dhimmel** [comment]
For interoperability, it'd probably be best to go with the Identifiers.org Central Registry identifier, which [in this case is](https://registry.identifiers.org/registry/clinicaltrials) `clinicaltrials`. So the citation would be like `clinicaltrials:NCT04292899`.

But perhaps the best general solution would be accept any identifiers.org compact IDs (CURIEs). Then:

1. make API call to https://resolver.api.identifiers.org/clinicaltrials:NCT04292899 to extract `compactIdentifierResolvedUrl`, in this case https://clinicaltrials.gov/ct2/show/NCT04292899.
2. Use translation-server to generate bibliographic metadata for the URL.

In any case, I think it's best to try to create Zotero translators for niche websites like this, since we don't want to keep increasing our maintenance burden.

**Comment by agitter** [comment]
I wasn't aware of the Identifiers.org registry.  That's a really great resource.

I like your general solution.  Being able to cite datasets, like `geo:GDS1234` via https://resolver.api.identifiers.org/geo:GDS1234, would be pretty cool. That's expanding the scope of this issue, so perhaps worth taking the discussion to a new more general issue.  There could be side effects or more maintenance required that I'm not thinking of.

**Comment by agitter** [comment]
@rdvelazquez's clinical trials translator pull request https://github.com/zotero/translators/pull/2153 was merged.  What is the next step to enable Manubot to use this new translator?  Does the translation-server at https://translate.manubot.org need to be updated following 
 https://github.com/manubot/manubot/issues/82#issuecomment-447037867?  It looks like `zotero/translation-server` has `zotero/translators` as a git submodule, so that would update the translators once the submodule is updated.

**Comment by dhimmel** [comment]
I SSHed to `translate.manubot.org` and ran the update commands in https://github.com/manubot/manubot/issues/82#issuecomment-447037867.

I added the following step to fast forward the translators submodule beyond the version in translation-server:

```shell
cd modules/translators
git pull origin master
```

The clinicaltrials translator is there:

![image](https://user-images.githubusercontent.com/1117703/81318695-a225d200-905c-11ea-8613-d94e05ec8b1b.png)

**Comment by agitter** [comment]
Thanks @dhimmel.  I see it working as well.  I believe we can close this issue.

**Comment by dhimmel** [comment]
Okay will close. For now, cite like `@url:https://clinicaltrials.gov/ct2/show/NCT04292899` until `@clinicaltrials:NCT04292899` is supported.
