### ISSUE TITLE
deprecation warning: `@coroutine` decorator is deprecation since python 3.8

### ISSUE THREAD

**Issue by slippycheeze** [manubot/manubot#257]
G'day.  Since `pandoc-manubot-cite` and the other `manubot` commands force deprecation warnings to be logger it always emits the deprecation for the `@coroutine` decorator in `Python 3.9.0`.  

Personally, I think you should not show that warning at the default logging level, but if you want to I guess time to require a newer python or port the code?

I've now disabled it by setting the log level to error, but I'm a little sad since that means I won't get any other warnings from the process.  I did try disabling it with `PYTHONWARNINGS=ignore::DeprecationWarning` which would normally work ... save that y'all add your own explicit filter to turn them on.  -_-

```
[INFO] Running filter pandoc-manubot-cite
## WARNING
/Users/slippycheeze/.local/pipx/venvs/manubot/lib/python3.9/site-packages/ratelimiter.py:127: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  __aexit__ = asyncio.coroutine(__exit__)
```

**Comment by dhimmel** [comment]
We've reported this issue upstream in https://github.com/RazerM/ratelimiter/issues/10 and there's even an open PR to fix it https://github.com/RazerM/ratelimiter/pull/11. Unfortunately, it's not clear whether `ratelimiter` is still maintained.

As a temporary solution, it'd be nice if manubot could silence this specific DeprecationWarning. It's more relevant to manubot developers rather than manubot users.

Other options might include:

- switching to a fork of ratelimiter.
- bringing the ratelimiter code into manubot, since it's small (Apache-2.0 licensed).
- switching to some other tool for ratelimiting requests.

**Comment by dhimmel** [comment]
> As a temporary solution, it'd be nice if manubot could silence this specific DeprecationWarning

Opened https://github.com/manubot/manubot/pull/259 to do this.
