### ISSUE TITLE
Allow "submanuscripts"

### ISSUE THREAD

**Issue by Adafede** [manubot/manubot#297]
Hi,

Thank you for your wonderful work with Manubot!

Would there be a way to allow metadata.yaml to be split per chapter, let's say so (it's pretty naive, might not be the right solution):

metadata.yaml: 
* authors_1:
  *  Bob
  * John
* authors_2:
  *  Alice
  * Bob

And then having in chapter 1: 11-front-matter-1.md with 
```
{## Template for listing authors ##}
{% for author in manubot.authors_1 %}
+ **{{author.name}}**<br>
...
```

And then chapter 2: 21-front-matter-2.md, 
```
{## Template for listing authors ##}
{% for author in manubot.authors_2 %}
+ **{{author.name}}**<br>
...
```
and so on?

Does this make sense to you?

Conceptually, do you disapprove 'merging' two manuscripts (as in a thesis, pure example) in one single manubot project? Have you already some examples/concerns?

**Comment by agitter** [comment]
This does make sense, and we have one example you may be able to use as a template.  The [COVID-19 review](https://github.com/greenelab/covid19-review) is a Manubot manuscript that combines 8 separate manuscripts.  The primary version on GitHub pages merges all 8 manuscripts and generates a (long) [HTML ](https://greenelab.github.io/covid19-review/) and [PDF ](https://greenelab.github.io/covid19-review/manuscript.pdf) document.  We also customized the Manubot build process to optionally output requested individual manuscripts in DOCX or TEX formats for preprint or journal submissions.  The TEX export requires some manual cleanup.  We do not currently generate HTML or PDF versions of the individual manuscripts.

If that may work for you, I can point you to some of the custom build script and metadata processing code we created in that project.  It has an open license so you are welcome to copy and modify it.

> Conceptually, do you disapprove 'merging' two manuscripts (as in a thesis, pure example) in one single manubot project?

Not at all.  It's fun seeing Manubot being customized in unexpected ways, and we're happy to give ideas about custom use cases even if we can't implement and support them.

**Comment by Adafede** [comment]
Thank you very much! Very impressive review, if you have some more technical details to share, would be very appreciated! 

From what I see in the metadata.yaml, all authors have associated manuscripts and methods but appear at the very beginning,  not split accordingly at each chapter. Would this be difficult to implement?

**Comment by agitter** [comment]
> all authors have associated manuscripts and methods but appear at the very beginning, not split accordingly at each chapter

Yes, we set up author metadata that way so we could still use the Manubot default author list for the merged manuscript and then customize the individual manuscripts.  Keeping a single author list and then using a YAML field or list makes sure the full author list is still passed to Pandoc (via the `author-meta` metadata).  If you don't want to write any new metadata processing code, something like this may work:

```
authors:
  -
    github: abc
    name: abc
    chapter1: True
    chapter2: True
authors:
  -
    github: xyz
    name: xyz
    chapter1: True
    chapter2: True
```

Then `00.front-matter.md` could check these fields when iterate through authors:
```
{% for author in manubot.authors %}
  {%- if author.chapter1 is defined and author.chapter1 %}
  **{{author.name}}**<br>
  {%- endif %}  
```

I haven't tested that syntax, but the idea is to only include authors associated with that chapter.

Alternatively, if you don't care about the author list in Pandoc, what you originally proposed should work.  If you define `authors1` and `authors2` in the metadata, those won't be recognized as special fields the same way `authors` is.  In `00.front-matter.md` you would access them as `authors1` and `authors2` instead of `manubot.authors1` and `manubot.authors2`

If you need heavier customization, in the COVID-19 review we added a new [Python script](https://github.com/greenelab/covid19-review/blob/master/build/update-author-metadata.py) that writes a new metadata.yaml file with relevant author information for a single individual manuscript and then re-run Manubot.  It also sorts that authors in the correct order for that individual manuscript.  This happens in the [build script](https://github.com/greenelab/covid19-review/blob/4670cde78a8da46e56a619946080dbabd55379e7/build/build.sh#L192).

**Comment by agitter** [comment]
The Manubot Python package has some [special processing](https://github.com/manubot/manubot/blob/c27e5b607a5724b21d198bcfea72c2687d09a262/manubot/process/util.py#L111-L142) that only runs on the list of `authors` in the metadata.  If you define a different field to represent the authors, like `authors1` and `authors2`, that processing won't happen.  That affects the author `affiliation_numbers`, `funders`, and `affiliations`.    The `funders` isn't being converted to a list so the template might need to be changed.

Is your manuscript public?  I could take a look at the metadata to make a more specific suggestion.

**Comment by Adafede** [comment]
It was actually simply bad formatting from my side with the funders (which did not show up until now).

Did:
```
funders: xxx
```
instead of
```
funders: 
 - xxx
```
which works fine!

Sadly it is not public (yet) but hopefully soon!

**Comment by Adafede** [comment]
Took a lot of time but here it is: https://github.com/manubot/catalog/pull/72
