### ISSUE TITLE
How do I use manubot cite programmatically?

### ISSUE THREAD

**Issue by staylorx** [manubot/manubot#308]
Hello. Thank you for the manubot cite feature; it works really well. I have a bit of code that I use for fetching markdown cites.

```py
def get_pmc_markdown(pmc_id: str) -> Dict[str, str]:
    # Use manubot-cite to fetch the formatted citation
    args = ["manubot", "cite", "--format=markdown", f"pmc:PMC{pmc_id}"]
    process = subprocess.run(args=args, capture_output=True, encoding="utf-8")
    process.check_returncode()

    return {
        "id": pmc_id,
        "cite": process.stdout,
    }
```

How can I use the manubot cite piece from python directly? I would like to do something like, 

```py
### ENTIRELY MADE UP ###
from manubot.cite import manubot_cite
def get_pmc_markdown(pmc_id: str) -> Dict[str, str]:
    # Use manubot-cite to fetch the formatted citation
    cite = manubot_cite(id=f"pmc:PMC{pmc_id}", format="markdown")
    return {
        "id": pmc_id,
        "cite": cite
    }
```

I'm running many lookups in parallel, but it loads up the OS on the subprocesses. All workable, and there's no show-stopper. I'd like to use it without subprocess.run(). I'm doing something similar to #135, and I can't help but think I could help if I could sort out using it programmatically.

Thank you!

**Comment by agitter** [comment]
I don't believe it is currently possible to do that with external-facing functions.  Manubot exposes the function `manubot.cite.citekey_to_csl_item` that takes a citekey (such as a PMC identifier) and returns a CSL item:
https://github.com/manubot/manubot/blob/a4af68125ab6bb322fdfb1689cfeec09f0cb1b60/manubot/cite/citekey.py#L251-L256

The CSL item is essentially a dict with some extra functions.  You can get the citation metadata, but it isn't formatted.

The command line `manubot cite` invokes pandoc behind the scenes to format the citekey(s) provided as command line arguments.  `call_pandoc` does that but is an internal function:
https://github.com/manubot/manubot/blob/a4af68125ab6bb322fdfb1689cfeec09f0cb1b60/manubot/cite/cite_command.py#L25

@dhimmel do you this exposing this functionality would be generally useful?  We could consider some refactoring to make another externally-facing function.

**Comment by staylorx** [comment]
Thanks for the info. That's useful to see it laid out. I can try working with `citekey_to_csl_item()` and see how far I get.

**Comment by dhimmel** [comment]
@staylorx a few questions:

You need references rendered as markdown right? So `citekey_to_csl_item` won't help that much since you still need to render the CSL Items using Pandoc.

How many PMC IDs do you have?

Are you running this multiple times for the same PMC IDs? If so you could cache the CSL JSON to avoid re-querying it.

The NCBI APIs have rate limiting that we account for at:

https://github.com/manubot/manubot/blob/a4af68125ab6bb322fdfb1689cfeec09f0cb1b60/manubot/cite/pubmed.py#L383-L384

But the multiple subprocess calls will bypass this.

Is parallelism really needed? Perhaps all that is really needed is a map from PMC ID to rendered markdown reference. The reason you can't run a single `manubot cite` command with multiple citation keys is that you want a one-to-one of input id to markdown reference?

The function that executes the `manubot cite` command is:

https://github.com/manubot/manubot/blob/a4af68125ab6bb322fdfb1689cfeec09f0cb1b60/manubot/cite/cite_command.py#L83-L85

It's not really designed for API usage, since it does things like directly passing the Pandoc stdout to the `manubot cite` stdout.

Some possible Manubot enhancements related to this issue:

- redesign `cli_cite` for better API usage.
- enable multi-threaded lookup in [`Citations.get_csl_items`](https://github.com/manubot/manubot/blob/a4af68125ab6bb322fdfb1689cfeec09f0cb1b60/manubot/cite/citations.py#L141-L163).

**Comment by staylorx** [comment]
You pretty much hit every single question I had, specifically the one about pandoc. The processes that I was replacing manubot cite with are also using the NCBI (and it's rate-limiting, even with a key is 10/minute). You mentioned multi-threaded lookups, and I had that working locally, but the subprocess calls to pandoc breakdown fast... which was probably the genesis of my question: how to use manubot-cite without the pandoc/subproc call/run. I've got that sorted in my head now.

So now that I know more, manubot-cite and I were doing the exact same thing. :) I think I thought manubot-cite magically got around using the pandoc as a subprocess -- and therefore would be easy to slot into a lambda/serverless like citeproc-py. But I see now, that's not the case. Not bad or good, just _is_. `citeproc-py` has some charm, but it's lacking serious love and attention. 

So overall, a really good walk through the technology. Thank you, thank you! for your considered replies. I can see an advantage to firming up manubot-cite as a class, and wrapping the CLI around it, and was what I _thought_ I was looking for in this issue. Ultimately though I think I was looking for a subprocess-free way of using manubot-cite. I'll close this, since I have my answer. Thanks again!
