### ISSUE TITLE
author order/annotation details

### ISSUE THREAD

**Issue by jessegmeyerlab** [manubot/manubot#315]
It seems like some repositories can randomize author order and there also might be a way to define the author order without re-ordering the list in metadata.yml? I looked at https://github.com/manubot/rootstock/blob/main/USAGE.md and the issues in rootstock and here but couldn't find how to do this. Could this be added to the documentation?

**Comment by jessegmeyerlab** [comment]
A related question is how to get the summary of words everyone contributed for determining author order? Sorry if I missed these points in the documentation

**Comment by dhimmel** [comment]
Hello! I'm guessing this is in relation to https://github.com/jessegmeyerlab/proteomics-tutorial. Was very excited by the announcement on [twitter](https://twitter.com/J_my_sci/status/1482045053849661445).

> there also might be a way to define the author order without re-ordering the list in metadata.yml

currently, authors are read via this [source code](https://github.com/manubot/manubot/blob/7a2a2df1a803420a15d9aeac712c6640a8b6b388/manubot/process/util.py#L193-L206). The order is determined solely by the order in the `authors` field.

> some repositories can randomize author order

See https://github.com/greenelab/deep-review/pull/997. It's not in the docs since randomizing authors was viewed as a rather custom operation.

Perhaps we could add an actual manubot option, such that you could put `manubot-randomize-author-order: true` in the `metadata.yaml` file.

If you want to brainstorm a bit more about your ideal author order behavior, we can decide whether a Manubot option or manuscript-specific solution makes more sense.

> summary of words everyone contributed for determining author order

There's some prototype code in [this notebook](https://github.com/greenelab/meta-review/blob/2482af490804891c7f00b248c4e7ef7f356a0730/analyses/deep-review-contrib/01.contrib-git.ipynb), which created the data for [this figure](https://greenelab.github.io/meta-review/v/2482af490804891c7f00b248c4e7ef7f356a0730/#fig:contrib). Note that it's based on commits to the main branch such that the counts don't represent the actual words in the final product.

Personally, I don't think word count contributed should be the only factor in author order, since it doesn't capture all types of contributions and not all words are equal, especially since these are words/characters in the markdown source (imagine words added in a large HTML comment in the source). But don't want to dissuade you from generating these metrics if you find them helpful.

**Comment by jessegmeyerlab** [comment]
Thanks Daniel! 

I liked the option to randomize before the paper is published to indicate that the order is up in the air until its decided. It would find it useful to be able to set an order option like I saw in the COVID review manuscript instead of copying and pasting to change the order. 

Thanks also for the link to the nb to the prototype code for counting based on commits to the main. 

I totally agree word count shouldn't be the only factor in determining author order. I see a unique opportunity to quantify contributions because we are using github to write and I want to leverage that to ensure authorship and ordering are fair. In the case of a review or tutorial word count is a great start. This will be less clear when there are experiments involved.

**Comment by agitter** [comment]
Randomizing all authors could be a generally useful feature that we may want Manubot to support.

The COVID-19 review uses a fair amount of customization for its ordering, in part because it defines separate orders for each of the individual manuscripts that are all part of the same Manubot project.  I could help guide you on reusing that custom code for your project, but we're unlikely to integrate it into Manubot.

> Maybe could also quantify the comments and reviews of pull requests?

I would really like better ways to track this.  Pull request review and discussion can be a very valuable contribution.  We could do something using the GitHub API but haven't prioritized it yet.

**Comment by dhimmel** [comment]
> I liked the option to randomize before the paper is published to indicate that the order is up in the air before it is finalized.

That's a cool idea!

> Randomizing all authors could be a generally useful feature that we may want Manubot to support.

Okay, I'll try to add this to Manubot soon. Thinking about what the best thing to use for a random seed is? Options include the git commit hash or the hash of the manuscript text. I like git commit hash but if the build is done locally with uncommited changes it can be stale... although stale here doesn't really matter.

**Comment by agitter** [comment]
The git commit hash makes sense to me as the seed.  It looks like that's what you used for the deep review v2.0 [randomization](https://github.com/greenelab/deep-review/blob/master/build/randomize-authors.py).

**Comment by dhimmel** [comment]
@jessegmeyerlab if you upgrade to the latest rootstock with https://github.com/manubot/rootstock/pull/456, you can use the following two options in metadata.yaml:

```yaml
# use this to randomize authors
manubot-randomize-author-order: true
# set this if you need to freeze the randomness
manubot-randomize-author-order-seed: "set a custom seed here, otherwise use git commit hash"
```

**Comment by jessegmeyerlab** [comment]
@dhimmel this is awesome thank you! I will try to do the upgrade soon and let you know if I have any issues

**Comment by jessegmeyerlab** [comment]
@dhimmel I think I almost got the changes adding following the instructions [here](https://github.com/manubot/rootstock/blob/main/SETUP.md#merging-upstream-rootstock-changes), but I'm stuck after the part with explicit code to run. Can you please advise on what to do next?  Here is where I'm at 
![image](https://user-images.githubusercontent.com/65188012/151208379-a940371b-508d-410a-9d45-83a648681f24.png)

**Comment by dhimmel** [comment]
Everything looks good. You can use the suggested command to push to the branch and then create a pull request.

Alternatively, you can just run this on the main branch, if you don't want to a use a PR and then push upstream.

```
# no PR method, assuming you're not working off of a fork.
git checkout main
git pull --no-ff --no-rebase rootstock main
git push origin main
```

**Comment by jessegmeyerlab** [comment]
Thanks! I think it worked. I set the option [here](https://github.com/jessegmeyerlab/proteomics-tutorial/blob/main/content/metadata.yaml)  but there are only two authors right now so it might take a few coin flips to see if it is working

**Comment by jessegmeyerlab** [comment]
looks like the randomization is working - https://jessegmeyerlab.github.io/proteomics-tutorial/v/065bac0ebf21a2c71fc3eb9766e18d39005f3193/
