### ISSUE TITLE
Manuscript build failing due to import error for `soft_unicode` from `markup_safe`

### ISSUE THREAD

**Issue by jaybee84** [manubot/manubot#329]
I am getting the following error when trying to commit changes to a PR in the [ml-in-rd repo](https://github.com/jaybee84/ml-in-rd):

`ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/markupsafe/__init__.py)`

It seems like this may be related to a version update : https://github.com/pallets/markupsafe/issues/284

Where would be the best place to add the necessary updates? - in manubot rootstock or individual forks? If this needs to be updated in individual forks, can you please point me to the best place to make this change. 

Thanks!
Jineta

**Comment by agitter** [comment]
This an unfortunate error due to the Jinja package that Manubot uses.  There are two possible solutions:
- (Preferred) As described in https://github.com/manubot/rootstock/issues/459, updating to the latest version of Manubot rootstock fixes this.  Follow the update [guide](https://github.com/manubot/rootstock/blob/main/SETUP.md#merging-upstream-rootstock-changes).
- Alternatively, you can pin the version of `markupsafe` in `environment.yml`.  See https://github.com/greenelab/covid19-review/pull/1082 for an example of this approach.  See the files changed tab in the pull request.

**Comment by jaybee84** [comment]
Thanks! @agitter .. That worked!
