### ISSUE TITLE
manubot cite supplies the first name and last name swapped

### ISSUE THREAD

**Issue by wlioen** [manubot/manubot#344]
This behavior already started a couple of weeks ago:

```
$ manubot cite isbn:9789027416261
## WARNING
Error parsing search_query output as JSON for isbn:9789027416261:
No items returned from any translator
## WARNING
Error in get_isbn_csl_item_zotero for 9789027416261 due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
```
```json
[
  {
    "type": "book",
    "title": "Authentiek leiderschap : een kwestie van wil en moed",
    "author": [
      {
        "given": "Bontje",
        "family": "J.C.B."
      }
    ],
    "issued": {
      "date-parts": [
        [
          2005
        ]
      ]
    },
    "publisher": "Spectrum",
    "publisher-place": "Utrecht",
    "edition": "1e dr",
    "abstract": "Studie over leidinggeven in bedrijven, praktisch uitgewerkt door interviews met vooraanstaande leidinggevenden",
    "ISBN": "9789027416261",
    "source": "WorldCat",
    "URL": "https://www.worldcat.org/oclc/65941902",
    "id": "tw8amfdb",
    "note": "This CSL Item was generated by Manubot v0.5.2 from its persistent identifier (standard_id).\nstandard_id: isbn:9789027416261"
  }
]
```

**Comment by agitter** [comment]
It looks like Zotero is unable to retrieve the metadata for this ISBN
```
search_query('isbn:9789027416261')
WARNING:root:Error parsing search_query output as JSON for isbn:9789027416261:
No items returned from any translator
```

The next ISBN retriever is Citoid.  The metadata is retrieved from https://en.wikipedia.org/api/rest_v1/data/citation/mediawiki/9789027416261.  If you visit that URL, you can see the problematic data:
`"author":[["J.C.B.","Bontje"]]`

These author name tokens are last, first so it is wrong here.  My interpretation is Manubot is parsing the metadata correctly but the source data is incorrect.

I expect it may be possible to correct that data, but I'm not sure where to do it.

**Comment by wlioen** [comment]
Thanks for your prompt reply! However, if I look at https://www.mediawiki.org/wiki/Citoid/API#mediawiki the order shown is also first, last?

**Comment by agitter** [comment]
I see.  We'll have to investigate this further.

It looks like the Manubot Citoid ISBN support was added in #79 and hasn't been changed since then.

**Comment by dhimmel** [comment]
>  if I look at https://www.mediawiki.org/wiki/Citoid/API#mediawiki the order shown is also first, last?

Nice catch, so looks like we should switch the name order when we parse the citoid response at:

https://github.com/manubot/manubot/blob/29dec5b86a173e66ee05f32581573089d1a0c7e2/manubot/cite/isbn.py#L103

@wlioen would you like to make that pull request?

Also noting a good workaround is to [set reference metadata](https://github.com/manubot/manufesto/blob/master/USAGE.md#reference-metadata) manually. It's often a good idea to even freeze the existing automatically generated reference metadata. This would help with this situation because it could preserve the zotero metadata when that was working and also give you an easy way to fix the incorrect author order.
