### ISSUE TITLE
Does `cite` batch requests for multiple IDs?

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/manubot#356]
This is a Manubot noob question. I considered a direct email but maybe others can benefit from the knowledge. I would've posted this as a discussion if available. 

When calling `manubot cite` with multiple ids -- e.g. `manubot cite doi:10.1098/rsif.2017.0387 pubmed:29424689 pmc:PMC5640425 arxiv:1806.05726` -- does Manubot attempt to consolidate the queries it makes to external services to improve performance? That is, say there are 7 `arxiv:` ids passed to Manubot, and the `arxiv` api happens to support batch querying multiple ids at once; will Manubot do that, or will it just take one id at a time?

This question is again related to `greenelab/lab-website-template`'s automatic citations process, where I'm currently calling Manubot for each source, 1 by 1. I was doing that for simplicity, and so I could control the progress logging output to my liking (e.g. using Manubot to cite source 1 of 213). But if I am going to be generating a lot of unnecessary api hits, I'd like to avoid that.

From what I can tell by looking at the code, manubot cite also seems to just take one id at a time? Are there any plans to do this in the future?

**Comment by dhimmel** [comment]
Manubot's citation metadata retrieval does not batch queries, such that every unique persistent identifier being cited triggers at least one API call. Many identifiers actually trigger multiple API calls for additional tasks like getting PubMed-DOI mappings, short DOIs, and zotero CSL JSON exports.

It's a good idea to batch queries, although many of the APIs don't support it. But as you note arXiv does. We went with one identifier one API query for simplicity and consistency between API methods. It would be a good amount of work to change that, so I think we're unlikely to pursue this change.

The main optimization I'd suggest for `manubot cite` is caching reference metadata using `--bibliography`. You can provide the output JSON/YAML from previous runs of `manubot cite` and references in these files will be used directly without re-performing the API calls. I could see two approaches:

- cache all references via `--bibliography` and periodically re-generate all references in case the metadata has changed
- cache only the references that are unlikely to change, i.e. those published in journals rather than preprints. Add to this list over time.

Do either of those approaches make sense for you?

> I considered a direct email but maybe others can benefit from the knowledge

Thank you! Issue much preferred.

**Comment by vincerubinetti** [comment]
Thanks for the response! I didn't actually even know that arXiv supported batch queries, I was just making an example. Though from what I've seen of these APIs, allowing batch queries is the exception, not the rule.

I think it's reasonable to keep it the way it is for simplicity. And this is good news for me because I don't have to change my code 😅 

The caching approach you suggested is basically what I've already implemented, though I did it outside of Manubot. I have a local yaml file that caches the raw Manubot response in a hash/dict by id. I check the cache for a matching id, and if it exists, I just use that and skip calling Manubot completely.

I hadn't thought of using the `--bibliography`, but I think that would require I refactor my "one id at a time" approach. Maybe it's worth considering some kind of cache param for the `cite` command like the `process` command has?
