### ISSUE TITLE
PMID citations not working anymore

### ISSUE THREAD

**Issue by jessegmeyerlab** [manubot/manubot#357]
Check out the github action here 
https://github.com/jessegmeyerlab/proteomics-tutorial/actions/runs/3727940950/jobs/6322525079

and the live manuscript with none of the PMIDs cited anymore here:
https://jessegmeyerlab.github.io/proteomics-tutorial/

Maybe this is a temporary error or maybe NIH changed their interface?

**Comment by agitter** [comment]
This is due to the NCBI API changes described in #354, so it is a permanent change. Updating to manubot v0.5.5 and/or the latest version of manubot-rootstock will fix this.

**Comment by jessegmeyerlab** [comment]
Thanks Anthony - I'm having trouble finding the instructions for updating the rootstock could you please share a link when you get a chance?

**Comment by jessegmeyerlab** [comment]
NVM I think its here:

https://github.com/manubot/rootstock/blob/main/SETUP.md#merging-upstream-rootstock-changes

**Comment by jessegmeyerlab** [comment]
noticing this issue again in the docx available as artifact here: https://github.com/jessegmeyerlab/proteomics-tutorial/actions/runs/6330246340

Was there another API change?

**Comment by dhimmel** [comment]
Hmm, I see a lot of errors in that [build log](https://github.com/jessegmeyerlab/proteomics-tutorial/actions/runs/6330246340/job/17192225965#step:8:323). The one that appears to be affecting the pubmed IDs is https://github.com/manubot/manubot/issues/367, so I think we need to upgrade rootstock.

**Comment by dhimmel** [comment]
https://github.com/manubot/rootstock/commit/48c7d75849f6fa24b2c2d6a529edc028f1b2d029 upgrades the `manubot` package version used by rootstock. So now if you upgrade your repo for the latest roostock, I'm hoping the pubmed references will work.

Many of the other issues in the log look like they could be due to misformatted citations. For example, the extra leading slash in `@doi:/10.1007/s13361-012-0377-z`. Hopefully once the pubmed errors are resolved, the log will be more manageable and allow you to fix any errors due to formatting.

If you'd like Manubot to fail when any citations are bad, you can do the following in `metadata.yaml`:

```yaml
pandoc:
  manubot-fail-on-errors: True
```

**Comment by jessegmeyerlab** [comment]
Thanks, pretty sure updated rootstock is working because the builds are taking more than twice as long again. I assume that is all the PMID citation fetching that wasn't working before. Will close this when I confirm a completed build
